# Generated by Django 5.0.6 on 2024-06-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='landlord_response',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
